name: SurvivalSkills
main: SurvivalSkills\Main
version: 1.1.0
api: [5.0.0]
description: Plugin Survival Skills dengan tampilan GUI
author: VsrStudio

commands:
  skill:
    description: Buka GUI skill pemain
    usage: "/skill"
    permission: skills.use
permissions:
  skills.use:
    description: Menggunakan perintah skill
    default: true
