name: SurvivalSkills
version: 1.0.0
main: SurvivalSkills\Main
api: 5.0.0
depend: [FormsUI]
commands:
  skill:
    description: Open your skill overview
    usage: /skill
    permission: survivalskills.use
permissions:
  survivalskills.use:
    description: Allows the player to use the /skill command
    default: true
